version: "3"
services:
  rippled:
    env_file: .env
    image: rippled_${NETWORK}:latest
    build:
      context: rippled
      args:
        rippled_ver: ${RIPPLED_VERSION}
        network: ${NETWORK}
    container_name: rippled_${NETWORK}_01
    ports:
      - ${RIPPLED_PORT}:5005
  ripple-lib:
    env_file: .env
    image: ripple_lib:latest
    build:
      context: ripple-lib
    container_name: ripple_lib_01
    ports:
      - ${RIPPLE_LIB_PORT}:80
    volumes:
      - ./ripple-lib/files:/home/ripple-lib
